import { existsSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { resolve } from "node:path";

/** A single line in a .env file — either preserved verbatim or a key assignment. */
type EnvLine =
  | { kind: "raw"; text: string }
  | { kind: "assign"; key: string; text: string };

/** True when a value must be double-quoted in dotenv format. */
function needsQuotes(value: string): boolean {
  if (!value) return false;
  return /[\s#"'\\]/.test(value) || /[\u0000-\u001f\u007f]/.test(value);
}

/** Escape a string for use inside double quotes in a .env file. */
function escapeQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/** Format a KEY=VALUE line for dotenv. */
export function formatEnvLine(key: string, value: string): string {
  if (needsQuotes(value)) {
    return `${key}="${escapeQuoted(value)}"`;
  }
  return `${key}=${value}`;
}

/** Parse KEY=VALUE assignments from a .env file, preserving comments and blanks. */
export function parseEnvFile(content: string): EnvLine[] {
  const lines: EnvLine[] = [];
  for (const raw of content.split(/\r?\n/)) {
    const trimmed = raw.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      lines.push({ kind: "raw", text: raw });
      continue;
    }
    const eq = raw.indexOf("=");
    if (eq <= 0) {
      lines.push({ kind: "raw", text: raw });
      continue;
    }
    const key = raw.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      lines.push({ kind: "raw", text: raw });
      continue;
    }
    lines.push({ kind: "assign", key, text: raw });
  }
  return lines;
}

/**
 * Merge vault secrets into existing .env content. Updates matching keys in place,
 * appends new keys at the end, and preserves comments and unrelated variables.
 */
export function mergeEnvContent(existing: string, updates: Record<string, string>): string {
  const lines = parseEnvFile(existing);
  const pending = new Map(Object.entries(updates));
  const out: string[] = [];

  for (const line of lines) {
    if (line.kind === "assign" && pending.has(line.key)) {
      out.push(formatEnvLine(line.key, pending.get(line.key)!));
      pending.delete(line.key);
    } else {
      out.push(line.text);
    }
  }

  if (pending.size > 0) {
    if (out.length > 0 && out[out.length - 1] !== "") {
      out.push("");
    }
    for (const [key, value] of [...pending.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      out.push(formatEnvLine(key, value));
    }
  }

  return out.join("\n") + (out.length ? "\n" : "");
}

/** Build a fresh .env file containing only the given secrets. */
export function buildEnvContent(secrets: Record<string, string>): string {
  const header = "# Generated by apivault — do not commit secrets to version control.\n";
  const body = Object.entries(secrets)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => formatEnvLine(key, value))
    .join("\n");
  return header + body + (body ? "\n" : "");
}

/** Write content to a .env path with owner-only permissions on Unix. */
export function writeEnvFile(filePath: string, content: string): void {
  const resolved = resolve(filePath);
  writeFileSync(resolved, content, "utf8");
  if (process.platform !== "win32") {
    try {
      chmodSync(resolved, 0o600);
    } catch {
      // best-effort
    }
  }
}

/** Read an existing .env file, or an empty string if it does not exist. */
export function readEnvFile(filePath: string): string {
  const resolved = resolve(filePath);
  if (!existsSync(resolved)) return "";
  return readFileSync(resolved, "utf8");
}
